services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Belsignum\DeleteProcessedImage\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Belsignum\DeleteProcessedImage\Controller\DeleteProcessedFileController:
    public: true

  Belsignum\DeleteProcessedImage\Backend\FileList\DeleteProcessedImageFileListActionListener:
    tags:
      - name: event.listener
        identifier: 'belsignum-deleteprocessedimage-filelist'
        event: TYPO3\CMS\Filelist\Event\ProcessFileListActionsEvent